# Generated by Django 5.1.1 on 2024-09-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetailsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('calendar', models.DateField()),
                ('duration', models.CharField(max_length=10)),
                ('time_slot', models.CharField(max_length=50)),
            ],
        ),
    ]
