# Generated by Django 5.1.1 on 2024-09-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetailstable',
            name='time_slot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
